# docker-compose file
# for compose v2
# set your ip address in {YOUR_LOCAL_IP}
# docker-compose -f ./docker-compose.yml up -d

version: "2"

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - app-tier
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 0511171AbAb
      MYSQL_DATABASE: javaShpargalki
      MYSQL_USER: abdullarily
      MYSQL_PASSWORD: 0511171a
volumes:
  mysql:
    driver: local